### ISSUE TITLE
Opinion: changelog should contain each commit of PRs

### ISSUE THREAD

**Issue by satazor** [uphold/github-changelog-generator#101]
Currently, the packages fetches all the pull requests after the last release and produces a new item for each PR on the changelog.

However, in my opinion, we should add each commit since the last release, which might or not be associated to a PR. This improves the granularity of the changelog. This has the advantage of also making this module work even if one commited directly to master 😇.

**Comment by satazor** [comment]
Related: https://github.com/uphold/github-changelog-generator/issues/101

I also have that opinion.

**Comment by waldyrious** [comment]
> Related: https://github.com/uphold/github-changelog-generator/issues/101

Is that a recursion joke? :laughing:

**Comment by waldyrious** [comment]
> we should add each commit since the last release, which might or not be associated to a PR.

> This has the advantage of also making this module work even if one commited directly to master innocent.

For what my opinion's worth, I tend to agree with the common recommendation that all changes to a collaborative repository should happen via pull requests, as that improves visibility of the changes, allows them to be reviewed, and offers consistency between simple changes that only require a single commit and those that would be better split into multiple related (but independent) commits.

In fact, the good practice of atomic commits would precisely lead to commit messages that aren't necessarily a good fit for a changelog, since the latter should focus on whole features / functional changes / user stories, rather than the steps required to achieve them.

If anything, I would prefer seeing mechanisms in place to prevent commits made without PRs.

**Comment by waldyrious** [comment]
@satazor since GitHub says that you closed this as "completed", could you confirm whether that is the case? I.e. did you make changes to this repo to enable commit-based changelogs, or did you simply use GitHub's default closing reason?
